function toolboxFigure(obj, varargin)

% ---------------------------------------
% Figure
% ---------------------------------------
obj.figure = figure(...
    'name',                [obj.name, ' (v', obj.version, '.', obj.date, ')'],...
    'tag',                 'toolboxfigure',...
    'numbertitle',         'off',...
    'menubar',             'none',...
    'toolbar',             'none',...
    'dockcontrols',        'on',...
    'visible',             'on',...
    'resize',              'on',...
    'selected',            'off',...
    'selectionhighlight',  'off',...
    'units',               'normalized',...
    'color',               [1.00, 1.00, 1.00],...
    'position',            [0.050, 0.125, 0.900, 0.800],...
    'sizechangedfcn',      '',...
    'resizefcn',           '');

end